# EPS CA0

### Soroush Mesforush Mashhad
#### Student No:810198472

# 1
In this excersice I have created a function that Gets N as number of elements from the user and prints N Fibonacci Elements

In [1]:
def Fibonacci(n):
        #Here I have Defined the needed variables including an empty array with the length of wanted elements
        T1=0
        T2=1
        Fib_Array=[None]*n
        #Here I have Checked For Wrong Values.
        if n<=0:
            print('Wrong Values!')
            return 
        #In this For loop I have created the Fibonacci Series Element by Element and at the end of it I return it.
        for i in range(0,n):
            Fib_Array[i]=T2
            T3 = T1+T2
            T1=T2
            T2=T3
        return Fib_Array
N = int(input('Enter Wanted Element Numbers : '))
Fib = Fibonacci(N)
if N>0:
    print(Fib)

Enter Wanted Element Numbers : 5
[1, 1, 2, 3, 5]


# 2
In this Excersise we create the Pascal Matrix

In [2]:
import numpy as np
def Pascal_Matrix(n):
    #Here I have defined my needed Variables including an nXn Numpy array.
    Temp=1
    Pas_Array=np.zeros([n,n])
    #Using these two for loops I have made the matrix
    for ln in range(0,n):
        for cn in range(0,ln+1):
            #Here I Check to see whether the position is appropriate to print the Vertical and Diagonal 1's
            if cn == 0 or cn == ln:
                Pas_Array[ln][cn]=1
            #Here I Create the other elements of the Matrix by adding the suitable elements accordingly.
            else:
                Pas_Array[ln][cn]=Pas_Array[ln-1][cn]+Pas_Array[ln-1][cn-1]
    return Pas_Array
N = int(input("Enter Wanted dimensions for nXn matrix :"))
Matrix=Pascal_Matrix(N)
print(Matrix)

Enter Wanted dimensions for nXn matrix :5
[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 2. 1. 0. 0.]
 [1. 3. 3. 1. 0.]
 [1. 4. 6. 4. 1.]]


# 3
In this part I have written a function that gets two words from the user and inserts one with the another.
p.s(Try typing bulletproof as word1 and BULLETPROOF as word2!,I have included my txt file in the Zip file of this CA.)

In [3]:
def Word_Changer(filename,word1,word2):
    #Here we open the files for reading and writing respectively.
    file1=open(filename,"r")
    file2=open("New.txt","w")
    #In this for loop we read the file line by line and replace the word with the used method then we close the file.
    for line in file1:
        file2.write(line.replace(word1,word2))
    file2.close()
    file1.close()
word1 = input('Enter word1:\n')
word2 = input('Enter word2:\n')
Word_Changer("Monologue.txt",word1,word2)

Enter word1:
bulletproof
Enter word2:
BULLETPROOF


# 4
Here I have created a function that reads the given Data.txt file and makes a list of dictionaries of the people in it.
p.s(There was a slight problem in the Data.txt file where in  * between two words the "space" had been forgotten which shall spoil the linesplit.

In [4]:
def Dict_Maker(Filename):
    #Here we open the file
    file = open(Filename,"r")
    #We pour the keys of our Dicts into an array.
    keys=file.readline().split(', ')
    #We create an empty List for the dictionaries
    Dict_Lists=[]
    count=0
    #In this loop we complete the necessary actions
    for line in file:
        #I pour the elements of each line with the desired split.
        Temp=line.split(" * ")
        #I make a Dict from each line which is each person.
        Dict=dict(zip(keys,Temp))
        #In the following loops I capitalize the names and convert the numbers from strings to integers.
        for i in range(0,2):
            Dict[keys[i]]=Dict[keys[i]].capitalize()
        for k in range(2,5):
            Dict[keys[k]]=int(Dict[keys[k]])
        #I append Each Dict to the previously created empty list.
        Dict_Lists.append(Dict)
        Dict={}
        count=count+1
    return Dict_Lists
Final_List=Dict_Maker("Data.txt")
print(Final_List)

[{'First Name': 'Alex', 'Last Name': 'James', 'Age': 25, 'Heigth': 190, 'Weigth': 84, 'Nationality\n': 'British\n'}, {'First Name': 'Sara', 'Last Name': 'Anderson', 'Age': 20, 'Heigth': 160, 'Weigth': 98, 'Nationality\n': 'American\n'}, {'First Name': 'Roberto', 'Last Name': 'Carlos', 'Age': 48, 'Heigth': 183, 'Weigth': 78, 'Nationality\n': 'Spanish\n'}, {'First Name': 'Mohammad', 'Last Name': 'Amiri', 'Age': 35, 'Heigth': 190, 'Weigth': 77, 'Nationality\n': 'Iranian '}]


# 5
Here I have created a function that reads a csv file and calculates the GPA(میانگین وزندار) of a student's grades in the Scale of 4 and also adds a column to the original csv file

In [5]:
import pandas as pd
def GPA_Calculator():
    #Here by using pandas I read the csv file and by using T.values.tolist() method I convert it into a list of lists.
    df = pd.read_csv('Transcripts.csv')
    data_list = df.T.values.tolist()
    # Here I create three lists accordingly(I also make a copy of the marks so I can change them without hesitation).
    Course_Names=data_list[0]
    Course_Credit=data_list[1]
    Course_Mark=data_list[2]
    Mark_Copy=Course_Mark
    #Here I Scale the Marks to 4.
    for i in range(0,len(Course_Mark)):
        if Mark_Copy[i]>=16 and Mark_Copy[i]<=20:
            Mark_Copy[i]=4
        elif Mark_Copy[i]>=14 and Mark_Copy[i]<16:
            Mark_Copy[i]=3
        elif Mark_Copy[i]>=12 and Mark_Copy[i]<14:
            Mark_Copy[i]=2
        elif Mark_Copy[i]>=10 and Mark_Copy[i]<11:
            Mark_Copy[i]=1
        elif Mark_Copy[i]>=0 and Mark_Copy[i]<10:
            Mark_Copy[i]=3
    #Here I Create two other Variables to calculate the GPA on the scale of 4
    Mark_Sum=0
    Credit_Sum=0
    #In this loop I calculate the needed sums then out of the loop I calculate the GPA.
    for k in range(0,len(Mark_Copy)):
        Mark_Sum=Mark_Sum+(Mark_Copy[k]*Course_Credit[k])
        Credit_Sum=Credit_Sum+Course_Credit[k]
    GPA_4=Mark_Sum/Credit_Sum
    print(GPA_4)
    #Here I add another column to the csv file.
    df["Mark_4"] = Mark_Copy
    df.to_csv("Transcripts.csv", index=False)
GPA_Calculator()    

3.2162162162162162
